declare -A VM_MAP

VM_MAP[SRV-01]="VM-Influx VM-Panorama VM-SQL VM-Dev-Pano-SCADA"
VM_MAP[SRV-02]="VM-Influx VM-Panorama VM-SQL VM-Dev-TIA-Process"
VM_MAP[SRV-ADM]="VM-Zabbix VM-ESETBridge VM-OPSI VM-ProxyMail VMWin11-Admin"
